## ----setup, include=FALSE------------------------------------------------
######################################################################
## This file contains the R source code for the analysis of the
## Naming Uncertainty article. The file is generated by knitr::purl 
## from the original Rmarkdown file. Due to copyright restrictions
## by the Journal. The full markdown file including the text + inline
## R code can unfurtunately not be provided.
##
## Author: Michael Höhle <http://www.math.su.se/~hoehle>
## Date: 2017-05-13
## License: GPLv3 - http://www.gnu.org/licenses/gpl-3.0.txt
######################################################################

knitr::opts_chunk$set(echo = FALSE, results='hide', message=FALSE)
##Create accompanying R file
##knitr::purl(input="Naming Uncertainty-r01.Rmd",output="Naming Uncertainty.R")

## ------------------------------------------------------------------------
library("dplyr")
library("magrittr")
#source(file.path("..","R","pbirthday_up.R"))
##Install package implementing the birthday problem with unequal occurrence probabilities
##devtools::install_github("hoehleatsu/birthdayproblem")
library(birthdayproblem)

##Load data - the newborn.RData file is produced by R/dataio.R
load(file=file.path("..","Data","newborn.RData"))
##Read results
if (file.exists(file.path("..","Data","theAnswer.Rdata"))) {
  load(file.path("..","Data","theAnswer.Rdata"))
}

##One global occurrence probability p not gender specific
newborn <- newborn %>% group_by(Sex) %>% mutate(Rank=rank(-Count, ties.method="min"))
newborn <- newborn %>% ungroup() %>%  mutate(p=Count/sum(Count))

top150Names <- newborn %>% ungroup %>% arrange(desc(Count)) %>% top_n(150,Count) %$% Name

################################################################################
## Helper function to convert a string of the type "NAME (X.Y‰)" into "Name" 
##
## Parameters:
##  firstName - the string to convert
## Returns:
##  a string
################################################################################
formatName <- function(firstName) {
  firstName <- gsub(" (.*)","",tolower(firstName)) #delete (rel freq in promille)
  firstName <- paste0(toupper(substr(firstName, 1, 1)), substr(firstName, 2, nchar(firstName)))
  return(firstName)
}

################################################################################
##Convert the integer rank to textual ordinal number, i.e. 1=1st
## Parameters:
##   int - integer to convert 
## Returns:
##  a string
################################################################################
int_to_textrank <- function(int) {
  paste0(int, switch(int, "1"="st", "2"="nd","3"="rd","4"="th","5"="th"))
}

## ------------------------------------------------------------------------
######################################################################
## Parametric bootstrap, but more memory efficient and parallelizable
######################################################################

library(foreach)
library(doMC)
registerDoMC(3) #run on 3 cores

##Data x now in aggregated form
bootstrap_ci_ranks_parallel <- function(x, Names, R=999, conf.level=0.95) {
  x <- x %>% ungroup %>% arrange(Sex,Name)
  idxNames <- pmatch(Names,x$Name)

  ##Compute ranks (parallelized)
  ranks <- foreach(i = seq_len(R+1), .combine="cbind") %dopar% {
    ##Create data, first iteration is always the actual data
    counts <- if (i==1) { 
      x %$% Count 
    } else {
      K <- rpois(1,sum(x$Count))
      rmultinom(1, size=K, prob=x %$% p)
    }
    ranks <- unlist(tapply(-counts, INDEX=x %$% Sex, FUN=rank,ties.method="min"))
    #Return only the rank for the requested names 
    ranks[idxNames]
  }
  ##Compute percentile CI on the ranks
  alpha <- (1 - conf.level)/2
  ranksci <- t(apply(ranks, 1, quantile, prob=c(alpha,1-alpha),type=3))
  ##Make a data.frame out of it and add a UCR rank re-order to 1, 2, 3,
  ranks_ci <- bind_cols(x[idxNames,],as.data.frame(ranksci)) %>% group_by(Sex) %>%
    mutate(ucr_reorder=as.numeric(factor(`2.5%`))) 
  
  ##Done
  return(list(rank_ci=ranks_ci,rank_boot=bind_cols(x[idxNames,],as.data.frame(ranks))))
}

## ---- BOOTRANKING, cache=TRUE, warning=FALSE-----------------------------
######################################################################
## Parallel parametrical bootstrap
######################################################################

set.seed(123)
conf.level <- 0.95
R <- 9999
system.time(b <- bootstrap_ci_ranks_parallel(newborn, Names=top150Names, R=R, conf.level=conf.level))

##Extract data.frame with the rank confidence interval for the names
newborn_rank <- b$rank_ci

##Show rankCI for the first 5 ranks
newborn_rank %>% group_by(Sex) %>% arrange(`2.5%`) %>% filter(ucr_reorder<=5)

##Group according to lower CI and concatenate all names having same rank here
nb <- newborn_rank %>% 
  mutate(Name=formatName(Name), Name_with_relfreq=paste0(Name,sprintf(" (%.1f‰)",p*1000))) %>% group_by(Sex, `2.5%`) %>%
  do( {
    data.frame(uc_rank=.$`2.5%`[1], fnames=paste(.$Name_with_relfreq, collapse=", "),Sex=.$Sex[1])
  }) %>% group_by(Sex) %>%
  select(Sex,uc_rank, fnames) %>% rename("UC_Rank"=uc_rank, "Baby Names"=fnames)

## ---- PREPRESULTS--------------------------------------------------------
topN <- 8
nb %>% do({head(.,n=topN)})

nb %>% filter(UC_Rank <= topN)
print(nb ,n=100)

##First with more than one per sex
first_tied <- nb %>% filter(grepl(",", `Baby Names`)) %>% slice(1)

boys_ucrank_tied <- first_tied %>% filter(Sex == "boys") %$% `Baby Names` %>% strsplit(split=", ") %>% .[[1]]
girls_ucrank_tied <- first_tied %>% filter(Sex == "girls") %$% `Baby Names` %>% strsplit(split=", ") %>% .[[1]]

## ---- echo=FALSE, warning=FALSE, results="asis"--------------------------
require(xtable)
nb <- nb %>% ungroup 
tab <- xtable::xtable(bind_cols(nb %>% ungroup %>% filter(Sex=="girls") %>% 
                                  head(n=topN) %>%  select(-Sex) %>%
                                  rename("First names (girls) "=`Baby Names`, "UCR (among girls) "=UC_Rank),
                                nb %>% ungroup %>% filter(Sex=="boys") %>% head(n=topN)  %>% select(-Sex) %>%
                                  rename("First names (boys) "=`Baby Names`,"UCR (among boys) "=UC_Rank)), caption=paste0("Table 1: Top-",topN," names according to the UCRs for girls and boys. In parenthesis the gender-specific relative frequencies per thousand."))
align(tab)[c(2:4)] <- "c"
print(tab,include.rownames=FALSE,type="html", html.table.attributes="border=5, padding=10, style=\"width=100%\"")

## ---- HISTODENS, fig.width=10,fig.height=5,dpi=600,fig.cap=paste0("Figure 1: Relative frequencies of the ",format(R+1, decimal.mark=".", big.mark=",",small.mark=",", small.interval=3)," bootstrap rank samples for each name in Table 1. Also shown is the resulting percentile based 95% CI for the name's rank - the circle shows the actual sex specific rank in the data."),warning=FALSE----
plot_histoci <- function(theSex, topN, ci_col,ylim=NULL) {
  ##Extract gender specific results from b
  ranks <- b$rank_boot %>% filter(Sex == theSex)
  cis <- b$rank_ci %>% filter(Sex == theSex)
  
  ##Idx of the last name to show?
  maxIdx <- newborn_rank %>% filter(Sex == theSex & ucr_reorder <= topN) %>%
    summarise(max_rank=max(Rank)) %$% max_rank
  
  idxRes <- grep("result\\.",names(ranks))
  foo <- t(ranks[,idxRes])
  namesIdx <- seq_len(maxIdx)
  
  ############################
  ##Histogram visualization
  ############################
  h <- apply(foo, 2, function(x) hist(x, breaks=c(seq_len(2*maxIdx),Inf),include.lowest=TRUE,right=FALSE,plot=FALSE)$density)
  colnames(h) <- ranks$Name
  
  ##Get highest rank obtained by the names considered in namesIdx
  maxRank2Show <- max(which(apply(h[,namesIdx],1,sum)>0))
  
  ##Colours and breaks in the density
  pal <- c(gray(1),gray(0.95),gray(0.8),gray(0.6),gray(0.2))
  breaks <- c(0,1e-12,0.025,0.1,0.5,1)
  
  ##Show the result
  image(x=namesIdx,y=seq_len(maxRank2Show),t(h[seq_len(maxRank2Show),namesIdx]),xaxt="n",xlab="",ylab="Rank",breaks=breaks,col=pal,ylim=ylim,main=paste0(toupper(substr(theSex,1,1)),substr(theSex,2,nchar(theSex))))
  axis(1,at=namesIdx,label=formatName(ranks$Name[namesIdx]),las=2)
  
  ## Add legend (only in one of the two panes)
  if (theSex == "girls") {
    legend(x="topleft",legend=c("(0%-2.5%)","[2.5%-10%)","[10%-50%)", "≥50%"),fill=pal[-1])
  }
  
  ##Show the rank confidence intervals
  for (i in 1:maxIdx) {
    points(i,i,col=ci_col,pch=20)
    lines(rep(i,2),cis[i,c("2.5%","97.5%")]+c(-0.5,0.5),col=ci_col,lwd=2)
    lines(rep(i,2)+c(-0.5,0.5),rep(cis[i,c("2.5%")]-0.5,2),col=ci_col,lwd=2)
    lines(rep(i,2)+c(-0.5,0.5),rep(cis[i,c("97.5%")]+0.5,2),col=ci_col,lwd=2)
  }
  axis(2,at=floor(ylim[1]+1):floor(ylim[2]),labels=FALSE)
  
  ##Done
  invisible()
}

##Make a plot containing the visualization for girls and boys
par(mfcol=c(1,2),mar=c(5.5,4.1,1.5,0.3))
plot_histoci(theSex="girls", topN=topN,ci_col="indianred3",ylim=c(0.5,17.5))
plot_histoci(theSex="boys", topN=topN,ci_col="steelblue",ylim=c(0.5,17.5))

## ------------------------------------------------------------------------
##Bootstrap birthday and olivia probability
bootstrap_probs <- function(x, Names, n=26L, R=999, conf.level=0.95) {
  x <- x %>% arrange(Sex,Name)
  ##idxNames <- which(x$Name %in% Names)
  idxNames <- pmatch(Names,x$Name)

  ##Compute ranks (parallelized)
  replicates <- foreach(i = seq_len(R+1), .combine="cbind") %dopar% {
    ##Create data, first iteration is always the actual data
    counts <- if (i==1) { 
      x %$% Count 
    } else {
      K <- rpois(1,sum(x$Count))
      rmultinom(1, size=K, prob=x %$% p)
    }
    ##Calculate probabilities of interest 1) collision of two 2) collision with specific name
    pbirth <- birthdayproblem::pbirthday_up(n=n, prob=counts / sum(counts), method="mase1992")$prob
    pclash <- 1 - dbinom(0, size=n-1, prob=(counts/sum(counts))[idxNames])
    c(pbirth,pclash)
  }

  ##Compute percentil CI on the ranks
  alpha <- 1-conf.level
  ci <- t(apply(replicates, 1, quantile, prob=c(alpha/2,1-alpha/2),type=3))
  res <- data.frame(What=c("pbirthday",paste0("p",Names)),cbind(hat=replicates[,1],ci))

  ##Done
  return(res)
}

## ---- BOOTPROBS, cache=TRUE----------------------------------------------
n <- 27L
p <- birthdayproblem::pbirthday_up(n,prob=newborn %$% p, method="mase1992")$prob
set.seed(123)
R <- 9999
##Generate the 2nd bootstrap sample
b2 <- bootstrap_probs(x=newborn, Names=top150Names,n=n,R=R, conf.level=conf.level)

##Birthday probability
pbday <- b2 %>% filter(What == "pbirthday")
sprintf("%.1f%% (%.0f%% CI: %.1f-%.1f%%)",100*pbday$hat, 100*conf.level, 100*pbday$X2.5.,100*pbday$X97.5.)

## ------------------------------------------------------------------------
##Beyond doubt no-colliders
b2 <- b2 %>% mutate(Name = substr(What,2,1e4))
noColliders <- b2 %>% filter(X97.5. < 0.05) %>%  inner_join(newborn, by="Name") %>% group_by(Sex) %>% top_n(1,X97.5.) 
heavyColliders <- b2 %>% inner_join(newborn, by="Name") %>% group_by(Sex) %>% top_n(1,X97.5.)

##Small formatter function to automatize text for the paper
make_text <- function(noCollider) {
  firstName <- formatName(noCollider$Name)
  sprintf("%s (%s rank %d)",firstName, noCollider$Sex, noCollider$Rank)
}

## ------------------------------------------------------------------------
##Store result
save(file=file.path("..","Data","results.RData"),list=c("top150Names","nb","newborn_rank","b","b2"))
if (FALSE) {
   load(file=file.path("..","Data","results.RData"))
}

## ------------------------------------------------------------------------
N <- newborn %>% distinct(Name) %>% nrow
n <- 27

## ----echo=FALSE----------------------------------------------------------
gmp::log10.bigz(gmp::chooseZ(N,n))

